# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the main branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

######
# This code will only check IaC under aws folder of the repository
######
name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Terraform init AWS:"
        cd ${{ github.workspace }}/aws
        terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: |
        echo "Terraform fmt AWS:"
        cd ${{ github.workspace }}/aws
        terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "Terraform plan AWS:"
        cd ${{ github.workspace }}/aws
        terraform plan -input=false
        
      # Download tenable.cs CLI and terrascan, currently download version of tenable.cs CLI if fixed in the URL, may require update later for newer version
    - name: Download tenable.cs CLI
      run: |
        curl https://downloads.accurics.com/cli/latest/accurics_linux --output /usr/local/bin/accurics
        chmod +x /usr/local/bin/accurics
        ls -la /usr/local/bin/accurics
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > /tmp/terrascan.tar.gz
        tar -xf /tmp/terrascan.tar.gz -C /tmp/ && rm /tmp/terrascan.tar.gz
        install /tmp/terrascan /usr/local/bin && rm /tmp/terrascan
        ls -la /usr/local/bin/terrascan

      # Print tenable.cs CLI and terrascan version
    - name: tenable.cs CLI version
      run: |
        echo "tenable.cs cli version"
        /usr/local/bin/accurics version
        echo "------"
        echo "terrascan version"
        /usr/local/bin/terrascan version

      # Run tenable.cs scan, by default the task will pass regardless of the IaC contain security issue or not
    - name: tenable.cs scan
      env:
        ACCURICS_APP_ID: ${{ secrets.ACCURICS_APP_ID }}
        ACCURICS_ENV_ID_AWS: ${{ secrets.ACCURICS_ENV_ID_AWS }}
        ACCURICS_REPO_NAME: ${{ github.server_url }}/${{ github.repository }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "ENV check:"
        echo "ACCURICS_APP_ID is $(echo $ACCURICS_APP_ID | wc -c) characters long"
        echo "ACCURICS_ENV_ID_AWS is $(echo $ACCURICS_ENV_ID_AWS | wc -c) characters long"
        echo "ACCURICS_REPO_NAME is $ACCURICS_REPO_NAME"
        echo ""
        echo -n "terraform version:"
        echo ""
        terraform version
        echo ""
        echo "LS PWD"
        echo "------"
        ls ${{ github.workspace }}
        echo "------"
        echo "accurics init AWS:"
        cd ${{ github.workspace }}/aws
        accurics init
        echo "------"
        echo "accurics scan AWS:"
        cd ${{ github.workspace }}/aws
        if 
          accurics scan -mode=pipeline -appurl=https://cloud.tenable.com/cns -token=$ACCURICS_APP_ID -project=$ACCURICS_ENV_ID_AWS -fail; then
          echo "IaC does not contain High severity policy violation, scan passed"
        else
          echo "IaC contain High severity policy violation, scan failed, results printed below"
          cat ${{ github.workspace}}/aws/accurics_report.json
          exit 1
        fi

      # Print the result in json format
    - name: Show Result
      run: |
        echo "AWS:"
        cat ${{ github.workspace}}/aws/accurics_report.json

      # Comment to avoid psuh the code
      # On push to main, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
#    - name: Terraform Apply
#      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#      run: terraform apply -auto-approve -input=false
